export const GET_ALL_BUSINESSES_REQUEST = "GET_ALL_BUSINESSES_REQUEST";
export const GET_ALL_BUSINESSES_SUCCESS = "GET_ALL_BUSINESSES_SUCCESS";
export const GET_ALL_BUSINESSES_FAILURE = "GET_ALL_BUSINESSES_FAILURE";

export const ADD_NEW_BUSINESS_REQUEST = "ADD_NEW_BUSINESS_REQUEST";
export const ADD_NEW_BUSINESS_SUCCESS = "ADD_NEW_BUSINESS_SUCCESS";
export const ADD_NEW_BUSINESS_FAILURE = "ADD_NEW_BUSINESS_FAILURE";

export const SEARCH_BUSINESS_REQUEST = "SEARCH_BUSINESS_REQUEST";
export const SEARCH_BUSINESS_SUCCESS = "SEARCH_BUSINESS_SUCCESS";
export const SEARCH_BUSINESS_FAILURE = "SEARCH_BUSINESS_FAILURE";
